# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8d065f5d58f057e6c6dbcc17e8ed355a7295ea542aad22830d849b0b2d10b70f74f77e7e2f491c732af7c8e9445cd45b4383d0d037976626cb200fcd0683aa39

test:
  secret_key_base: 94e755444c821bbecea6273ac18e69bb03eefd1657343b44c90213845c0b840f58dc267360c04386f41d2663f6d4fd95e3277697b1ce51c4a60de26a4dbeb6e9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
